// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ5e5IyhFEKbTipEYbSpYe9HNrW9HpHbI',
    appId: '1:420403028232:web:d9dd2b00dddbf129d60cbd',
    messagingSenderId: '420403028232',
    projectId: 'flutterauth-bec3c',
    authDomain: 'flutterauth-bec3c.firebaseapp.com',
    storageBucket: 'flutterauth-bec3c.appspot.com',
    measurementId: 'G-RE7Z7P3HJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs9sMpfykQLgs04QWdo_zWp1tGv17Jp2A',
    appId: '1:420403028232:android:9fe2df6e2a6dd440d60cbd',
    messagingSenderId: '420403028232',
    projectId: 'flutterauth-bec3c',
    storageBucket: 'flutterauth-bec3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5R1YXQT_PxSAVrtN5Smwt4oeny30QfjU',
    appId: '1:420403028232:ios:8dd5943b7f591cfbd60cbd',
    messagingSenderId: '42040 3028232',
    projectId: 'flutterauth-bec3c',
    storageBucket: 'flutterauth-bec3c.appspot.com',
    iosBundleId: 'com.example.flutterWidgets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5R1YXQT_PxSAVrtN5Smwt4oeny30QfjU',
    appId: '1:420403028232:ios:308cf2fe394bcf78d60cbd',
    messagingSenderId: '420403028232',
    projectId: 'flutterauth-bec3c',
    storageBucket: 'flutterauth-bec3c.appspot.com',
    iosBundleId: 'com.example.flutterWidgets.RunnerTests',
  );
}
